### ISSUE TITLE
Issue with 15_3Sum.go

### ISSUE THREAD

**Issue by beck79** [turabaev69/My_Leetcode_stories#1]
Hello when I run https://github.com/turabaev69/My_Leetcode_stories/blob/main/Golang/15.%203Sum/15_3Sum.go on my vs code, I got the issue 
prog.go:5:1: expected 'package', found 'import' 

could you please help me?

**Comment by turabaev69** [comment]
just import main

package main 
that line above, paste it on the top of the file

**Comment by turabaev69** [comment]
just import main

package main
that line above, paste it on the top of the file

**Comment by turabaev69** [comment]
just import main

package main
that line above, paste it on the top of the file
